### ISSUE TITLE
Feature: Add page routing

### ISSUE THREAD

**Issue by mingfang** [cloudflare/workers-web-experiments#32]
Thank you for writing the micro frontend blog and this repo.
I've learned a lot about Qwik and Cloudflare Workers.

Please add page routing support, ideally using Qwik-City.
Thanks again.

**Comment by mingfang** [comment]
Maybe the easiest thing to do is to add Qwik-City routing to Main.
Each "page" will contain different FragmentPlaceholders to stitch fragments together.
Let me fork and give it a try.

**Comment by petebacondarwin** [comment]
OK @mingfang  - thanks.
Just be aware that QwikCity doesn't work out-of-the-box on Workers without "Cloudflare Pages", which this demo is not using, so you might find some friction getting it up and running.

**Comment by petebacondarwin** [comment]
Closing as this request is out of scope for the cloud-gallery demo.
